apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastro-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cadastro-deployment
    spec:
      containers:
      - name: cadastro-container
        image: diogobruno06/cadastro-lanhouse:1.1
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: cadastro-deployment
