apiVersion: v1
kind: Service
metadata:
  name: postgres-service-nodeport
spec:
  selector:
    app: postgres-deployment
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30050
